coverage:
  ignore:
    - "eomaps/qtcompanion" # ignore qtcompanion gui for now (it's untested)
  status:
    project:
      default:
        threshold: 100%
    patch:
      default:
        threshold: 100%
