name: eomaps
channels:
  - conda-forge

dependencies:
  - python = 3.11
  - numpy
  - scipy
  - pandas
  - geopandas
  - matplotlib >=3.4
  - cartopy >=0.20.0
  - descartes
  - mapclassify
  - pyproj
  # --------------for data-shading
  - datashader
  # --------------for GeoTIFF and NetCDF files
  - netcdf4
  - xarray
  - rioxarray
  # --------------for WebMaps
  - owslib
  - requests
  - cairosvg
  # --------------to support multiple Qt versions
  - qtpy
  # --------------for testing
  - coveralls
  - pytest
  - pytest-cov
  # --------------for building the docs
  - sphinx-copybutton
  - sphinx
  - docutils
  - sphinx_rtd_theme
